# Generated by Django 3.2.14 on 2022-07-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0002_add_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('count', models.IntegerField()),
                ('list_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.listusers')),
            ],
        ),
    ]
