# Generated by Django 3.2.14 on 2022-07-21 19:44
from django.db import migrations
from django.contrib.auth.models import User
from django.db.models import F

def user_monitoring(apps, shema_editors):
    # Users = apps.get_models('users', 'User')
    Monitoring = apps.get_model('home', 'Monitoring')
    print("!!!!  ", Monitoring)
    for user in User.objects.all():
        if Monitoring.objects.filter(day=user.date_joined).exists():
            monitor = Monitoring.objects.filter(day=user.date_joined)
            monitor.update(count=F('count') + 1)
        else:
            monitor = Monitoring(day=user.date_joined, count=1)
            monitor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [migrations.RunPython(user_monitoring)
    ]
