# Generated by Django 3.2.14 on 2022-07-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220721_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='monitoring',
            name='list_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.listusers'),
        ),
    ]
