# Generated by Django 3.2.14 on 2022-07-22 10:10

from django.db import migrations
from django.contrib.auth.models import User
from django.db.models import F

def user_monitoring(apps, shema_editors):
    # Users = apps.get_models('users', 'User')
    StatisticUsers = apps.get_model('monitor', 'StatisticUsers')
    for user in User.objects.all():
        if StatisticUsers.objects.filter(day=user.date_joined).exists():
            monitor = StatisticUsers.objects.filter(day=user.date_joined)
            monitor.update(count=F('count') + 1)
        else:
            monitor = StatisticUsers(day=user.date_joined, count=1)
            monitor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_listusers_statisticusers'),
    ]

    operations = [
        migrations.RunPython(user_monitoring)
    ]
